stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      pool: Default
    continueOnError: true
    steps:
    - script: echo "hello to my first Build"
- stage: dev_deploy
  jobs:
  - deployment: dev_deploy
    pool:
      pool: Default
    environment: 'dev-hello'
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo "hello, dev world !!!"
- stage: qa_deploy
  jobs:
  - deployment: qa_deploy
    pool:
      pool: Default
    environment: 'qa-hello'
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo "hello, qa world !!!"